module.exports.js = require('./js')
module.exports.typescript = require('./typescript')
module.exports.nuxt = require('./nuxt')
module.exports.nestjs = require('./nestjs')
module.exports.react = require('./react')
